import json
from pathlib import Path
SHEET = str(Path(__file__).resolve().parent.parent / "auto_agent/data/artstyle/styles/semoji_character_sheet.png")
STYLE = """The attached image is the official Semoji character sheet. Use it ONLY as the drawing-style reference and draw a completely NEW image described below (a new composition, new people, new clothes).
Match the attached image exactly for how bodies and faces are drawn: head size relative to the whole figure, short limbs, mitten-like hands, small solid black dot eyes, simple thick eyebrows, a soft pink cheek blush, a nose implied by one flat shadow plane.
CHARACTER PROPORTIONS — apply to every person in the frame: stylized cartoon proportions, three and a half heads tall. The head is very large relative to the body — one head height equals roughly 28 percent of the full standing figure. Shoulders sit just below the chin. Legs are short and thick, arms are short with mitten-like hands. This is the single most important requirement of the image.
Rendering: borderless flat 2D vector illustration. Every form is built from flat solid color planes meeting edge to edge, each surface one uniform tone with at most one slightly darker flat shadow plane. Lighting is expressed only as contrast between darker and lighter color planes. Clean, smooth, matte, pristine vector fills everywhere, including the background.
The image is purely pictorial: all signboards, labels and papers are left blank and plain."""
CHROMA = "Background: one perfectly flat solid chroma green #00B140 filling the entire canvas edge to edge, with the subject isolated in the center and generous green margin on all sides. The subject itself contains no green."
items = [
 ("s01_family", "16:9", "1792x1024",
  "Scene: a joyful Korean family of three celebrating a graduation day at a round table in a Korean-Chinese restaurant. People in frame, exactly 3: (1) the graduate, a teenage boy in a navy school uniform holding a bouquet of yellow flowers in one arm, slurping black-bean-sauce noodles with chopsticks, a little black sauce on his cheek; (2) the mother, 40s, short permed dark brown hair, pink cardigan, smiling proudly; (3) the father, 40s, neat short black hair, grey suit jacket, laughing. Three white porcelain bowls of jjajangmyeon (noodles covered with glossy dark brown-black sauce, diced onion, julienned cucumber) and a plate of yellow pickled radish on the table. Background: deep Chinese-red restaurant wall #B3212B with a large round moon-gate window and two hanging red paper lanterns. The bottom 15% of the frame is the plain table surface. Palette: #B3212B red, #F3E6CF cream, #2B2B2B black sauce, #F2C14E gold, #1F3A5F navy."),
 ("s02_dock", "16:9", "1792x1024",
  "Scene: the busy harbor pier of Incheon (Jemulpo) in the 1880s. People in frame, exactly 3 Chinese dock laborers from Shandong taking a meal break, sitting on low wooden crates in the foreground: each wears a loose faded indigo cotton jacket and trousers, cloth shoes, and a long single black braided queue hairstyle with the front of the head shaved; one is lifting noodles high with chopsticks from a rough brown clay bowl, one is drinking from his bowl, one is laughing. Burlap rice sacks and wooden barrels stacked beside them. Midground: a wooden pier with an old steamship with a tall black smokestack and two Chinese junk sailing boats with brown batten sails. Far background: soft grey-blue hills and a pale sky. Palette: #3E5C7A indigo, #C9A66B burlap, #8FB3C9 sky, #6B4A2F wood, #F3E6CF cream."),
 ("s03_restaurant", "16:9", "1792x1024",
  "Scene: the front of a handsome two-story Chinese restaurant building on a sloped street of Incheon Chinatown in the early 1900s, seen straight on from across the street. Red brick walls, a second-floor wooden balcony with carved red railings, dark green window frames, a grey tiled roof edge, red paper lanterns hanging along the balcony. Above the main double door hangs one large plain black lacquered wooden signboard with a gold border, completely blank, placed in the upper-middle of the frame. A cobblestone street in the foreground. Nobody on the street. Flat light-blue sky with two simple flat clouds. Palette: #A83A32 brick red, #1E1E1E signboard black, #D4A537 gold, #9CC7D8 sky, #5B6B4F dark green."),
 ("s03_woo", "1:1", "1024x1024",
  "Subject: a full-body standing portrait of a Chinese restaurant owner in 1905, a man in his 30s from Shandong: round face, short black moustache, black round skullcap, dark blue long traditional Chinese robe (changshan) with cloth frog buttons, black cloth shoes. He smiles proudly and extends one open palm to the side as if presenting his new restaurant. " + CHROMA),
 ("s05_chunjang", "1:1", "1024x1024",
  "Subject: a large round-bellied brown glazed ceramic jar full of glossy jet-black fermented black bean paste (chunjang), with a plain blank cream paper label tied on the front. Beside it a small white bowl of the black paste and a wooden spoon dripping thick shiny black paste. Still life, three-quarter view, grouped tightly together. " + CHROMA),
 ("s05_bowl", "1:1", "1024x1024",
  "Subject: one appetizing bowl of Korean jjajangmyeon seen from a high three-quarter angle: a white porcelain bowl with a thin red rim band, thick wheat noodles covered with glossy dark brown-black bean sauce with diced onions, cubes of pork and zucchini, topped with a small pile of fresh julienned cucumber, a pair of wooden chopsticks resting on the rim, a little steam shaped as three soft flat white curls. " + CHROMA),
 ("s06_kid", "1:1", "1024x1024",
  "Subject: upper-body portrait of a delighted little Korean boy about 8 years old with a short bowl haircut and a yellow T-shirt, slurping a long strand of noodles, a big smear of black bean sauce around his mouth, eyes squeezed shut in bliss, cheeks blushing pink, holding chopsticks in one hand. " + CHROMA),
 ("s06_crowd", "16:9", "1792x1024",
  "Scene: four people from different eras of Korean history standing side by side in a row facing the viewer, each happily holding up a bowl of black-bean-sauce noodles, like a family photo across a century. People in frame, exactly 4, left to right: (1) a 1900s Chinese dock laborer with a long braided queue and loose indigo cotton clothes; (2) a 1960s Korean factory worker woman with short curly hair, grey work uniform and white headscarf; (3) a 1980s Korean high school boy with a buzz cut in a black stand-collar school uniform; (4) a present-day Korean office worker woman with a long ponytail, white blouse and ID lanyard. Background: flat Chinese-red wall #B3212B with a subtle darker red cloud pattern and gold sparkles. Palette: #B3212B red, #F2C14E gold, #3E5C7A indigo, #F3E6CF cream, #2B2B2B black."),
 ("s05_factory", "16:9", "1792x1024",
  "Scene: inside a small Korean food factory in the late 1940s. People in frame, exactly 1: a Chinese-Korean food maker in his 40s with short black hair, a white work shirt with rolled sleeves and a long brown apron, stirring a huge black iron cauldron of glossy black bean paste with a long wooden paddle while pouring a thick golden amber caramel syrup into it from a copper pot; the golden syrup swirls into the black paste. Behind him rows of brown ceramic fermentation jars on wooden shelves and a small window with warm light. Palette: #2B2B2B black paste, #E0A030 caramel gold, #7A4E2D wood brown, #F3E6CF cream, #B3212B red accent."),
]
with open("assets/gen/prompts.jsonl","w") as f:
    for i,ar,size,body in items:
        f.write(json.dumps({"id":i,"ar":ar,"size":size,"prompt":STYLE+"\n\n"+body,"output_path":f"{i}.png","ref_images":[SHEET]},ensure_ascii=False)+"\n")
print(len(items))
